/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author CLAUDIO
 */
public class Ventana extends javax.swing.JFrame {
    private Timer tiempo;
    private int centesimasSegundo=0,segundos=0,minutos=0,horas=0;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           centesimasSegundo++;
           if(centesimasSegundo==100){
               segundos++;
               centesimasSegundo = 0;
           }
           if(segundos ==60){
               minutos++;
               segundos=0;               
           }
           if(minutos==60){
               horas++;
               minutos=0;
           }
          actualizaretiquetatiempo();
        }
    };
    
    private void actualizaretiquetatiempo(){
        String texto = (horas<=9?"0":"")+horas +":"+ (minutos<=9?"0":"")+minutos +":"+ (segundos<=9?"0":"")+segundos+":" + (centesimasSegundo<=9?"0":"")+centesimasSegundo;
        etiquetatiempo.setText(texto);
    }
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        tiempo = new Timer (10,acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        cronometro = new javax.swing.JLabel();
        etiquetacronometro = new javax.swing.JLabel();
        etiquetatiempo = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetafondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronometro.png"))); // NOI18N
        cronometro.setText("jLabel1");
        panel.add(cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 150));

        etiquetacronometro.setFont(new java.awt.Font("Century751 SeBd BT", 2, 36)); // NOI18N
        etiquetacronometro.setText("Cronómetro");
        panel.add(etiquetacronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 210, -1));

        etiquetatiempo.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        etiquetatiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetatiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetatiempo.setText("00:00:00:00");
        etiquetatiempo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(etiquetatiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 270, 40));

        botonIniciar.setBackground(new java.awt.Color(0, 204, 204));
        botonIniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        botonPausar.setBackground(new java.awt.Color(0, 204, 204));
        botonPausar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        botonDetener.setBackground(new java.awt.Color(0, 204, 204));
        botonDetener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        etiquetafondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fonauto.jpg"))); // NOI18N
        panel.add(etiquetafondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
      tiempo.start();
      botonIniciar.setEnabled(false);
      botonIniciar.setText("Reaundar");
      botonPausar.setEnabled(true);
      botonDetener.setEnabled(true);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
       tiempo.stop();
       botonIniciar.setEnabled(true);
       botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }
        
        botonIniciar.setText("Iniciar");
        botonPausar.setEnabled(false);
        botonDetener.setEnabled(true);
        
        horas=0;
        minutos=0;
        segundos=0;
        centesimasSegundo=0;
        
        actualizaretiquetatiempo();
        
    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel cronometro;
    private javax.swing.JLabel etiquetacronometro;
    private javax.swing.JLabel etiquetafondo;
    private javax.swing.JLabel etiquetatiempo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
